### ISSUE TITLE
Crash on "PICs-"

### ISSUE THREAD

**Issue by repent** [repent/acromatic#38]
Managed to crash it with "PICs-" -- not sure what type of dash, I think it was a hyphen.

Error:

D, [2021-04-02T21:15:39.598782 #15535] DEBUG -- :    (1.3ms)  commit transaction
D, [2021-04-02T21:15:39.598926 #15535] DEBUG -- :    (0.0ms)  begin transaction
D, [2021-04-02T21:15:39.600109 #15535] DEBUG -- :   SQL (0.2ms)  UPDATE "acronyms" SET "document_id" = ?, "updated_at" = ? WHERE "acronyms"."id" = ?  [["document_id", 1347], ["updated_at", "2021-04-02 21:15:39.599245"], ["id", 119326]]
D, [2021-04-02T21:15:39.601668 #15535] DEBUG -- :    (1.2ms)  commit transaction
D, [2021-04-02T21:15:39.602444 #15535] DEBUG -- :   Acronym Load (0.1ms)  SELECT  "acronyms".* FROM "acronyms" WHERE "acronyms"."document_id" = ? AND "acronyms"."initialism" = ?  ORDER BY "acronyms"."id" ASC LIMIT 1  [["document_id", 1347], ["initialism", "STCW"]]
D, [2021-04-02T21:15:39.603524 #15535] DEBUG -- :    (0.1ms)  begin transaction
D, [2021-04-02T21:15:39.604163 #15535] DEBUG -- :    (0.0ms)  commit transaction
D, [2021-04-02T21:15:39.604689 #15535] DEBUG -- :   CACHE (0.0ms)  SELECT  "acronyms".* FROM "acronyms" WHERE "acronyms"."document_id" = ? AND "acronyms"."initialism" = ?  ORDER BY "acronyms"."id" ASC LIMIT 1  [["document_id", 1347], ["initialism", "STCW"]]
D, [2021-04-02T21:15:39.605734 #15535] DEBUG -- :    (0.1ms)  begin transaction
D, [2021-04-02T21:15:39.606255 #15535] DEBUG -- :    (0.0ms)  commit transaction
D, [2021-04-02T21:15:39.606908 #15535] DEBUG -- :   Acronym Load (0.1ms)  SELECT  "acronyms".* FROM "acronyms" WHERE "acronyms"."document_id" = ? AND "acronyms"."initialism" = ?  ORDER BY "acronyms"."id" ASC LIMIT 1  [["document_id", 1347], ["initialism", "PICs-"]]
I, [2021-04-02T21:15:39.608110 #15535]  INFO -- : Completed 500 Internal Server Error in 1492ms (ActiveRecord: 366.6ms)
F, [2021-04-02T21:15:39.609079 #15535] FATAL -- :
RuntimeError (Acronym PICs- not re-found in the text document):
  app/models/document.rb:310:in `get_context'
  app/models/document.rb:186:in `block in trawl'
  app/models/document.rb:100:in `scan'
  app/models/document.rb:100:in `trawl'
  app/controllers/documents_controller.rb:42:in `block (2 levels) in create'
  app/controllers/documents_controller.rb:39:in `create'

**Comment by repent** [comment]
I, [2021-04-02T21:20:05.710609 #15535]  INFO -- : Completed 500 Internal Server Error in 2617ms (ActiveRecord: 667.7ms)
F, [2021-04-02T21:20:05.711240 #15535] FATAL -- :
RuntimeError (Acronym PIFS(15)7 not re-found in the text document):
  app/models/document.rb:310:in `get_context'
  app/models/document.rb:186:in `block in trawl'
  app/models/document.rb:100:in `scan'
  app/models/document.rb:100:in `trawl'
  app/controllers/documents_controller.rb:42:in `block (2 levels) in create'
  app/controllers/documents_controller.rb:39:in `create'
