### ISSUE TITLE
ArgumentError (invalid byte sequence in UTF-8)

### ISSUE THREAD

**Issue by repent** [repent/acromatic#4]
I, [2017-04-12T09:34:41.695744 #12690]  INFO -- : Completed 500 Internal Server Error in 102ms (ActiveRecord: 3.0ms)
F, [2017-04-12T09:34:41.696723 #12690] FATAL -- :
ArgumentError (invalid byte sequence in UTF-8):
  app/models/document.rb:40:in `scan'
  app/models/document.rb:40:in `trawl'
  app/controllers/documents_controller.rb:32:in `block (2 levels) in create'
  app/controllers/documents_controller.rb:29:in `create'

**Comment by repent** [comment]
This only happens with documents with the extension .DOCX.
docx2txt handles files inconsistently depending on the case of the extension.
